# Generated by Django 5.0.6 on 2025-12-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
