# Generated by Django 5.0.6 on 2025-12-26 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_languagecenter_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagecenter',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='languagecenter',
            name='features',
            field=models.TextField(blank=True, help_text='HTML list or paragraphs for features'),
        ),
        migrations.AddField(
            model_name='languagecenter',
            name='fees',
            field=models.TextField(blank=True, help_text='HTML table/description for fees'),
        ),
        migrations.AddField(
            model_name='languagecenter',
            name='location_info',
            field=models.TextField(blank=True, help_text='HTML content for location/hours'),
        ),
        migrations.AddField(
            model_name='languagecenter',
            name='programs',
            field=models.TextField(blank=True, help_text='HTML content for programs'),
        ),
        migrations.CreateModel(
            name='LanguageCenterApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('country_of_residence', models.CharField(max_length=150)),
                ('study_duration', models.PositiveIntegerField(help_text='Number of months')),
                ('email', models.EmailField(max_length=254)),
                ('country_code', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=30)),
                ('passport_photo', models.FileField(upload_to='applications/passport/')),
                ('personal_photo', models.FileField(upload_to='applications/personal/')),
                ('high_school_certificate', models.FileField(upload_to='applications/certificates/')),
                ('accept_terms', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.languagecenter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
